service: aws-node-express-typescript-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: ${opt:region, 'eu-west-3'}

# functions
functions:
  hello:
    handler: src/functions/hello.handler
    events:
      - http:
          path: serverlessSetup/hello
          method: get

  goodbye:
    handler: src/functions/goodbye.handler
    events:
      - http:
          path: serverlessSetup/goodbye
          method: post

# Serverless plugins
plugins:
  - serverless-plugin-typescript
  - serverless-offline
